# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'small_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(180, 141, 371, 361))
        self.graphicsView.setObjectName("graphicsView")
        self.linesPerFrame = QtWidgets.QLineEdit(self.centralwidget)
        self.linesPerFrame.setGeometry(QtCore.QRect(200, 200, 113, 21))
        self.linesPerFrame.setText("")
        self.linesPerFrame.setObjectName("linesPerFrame")
        self.History = QtWidgets.QTextBrowser(self.centralwidget)
        self.History.setGeometry(QtCore.QRect(335, 170, 211, 111))
        self.History.setObjectName("History")
        self.initializeButton = QtWidgets.QPushButton(self.centralwidget)
        self.initializeButton.setGeometry(QtCore.QRect(180, 240, 151, 32))
        self.initializeButton.setObjectName("initializeButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(410, 150, 60, 16))
        self.label.setObjectName("label")
        self.linesPerFrameLabel = QtWidgets.QLabel(self.centralwidget)
        self.linesPerFrameLabel.setGeometry(QtCore.QRect(200, 180, 71, 16))
        self.linesPerFrameLabel.setObjectName("linesPerFrameLabel")
        self.pumpsOnPlot = QtWidgets.QGraphicsView(self.centralwidget)
        self.pumpsOnPlot.setGeometry(QtCore.QRect(190, 331, 161, 161))
        self.pumpsOnPlot.setObjectName("pumpsOnPlot")
        self.pumpsOffPlot = QtWidgets.QGraphicsView(self.centralwidget)
        self.pumpsOffPlot.setGeometry(QtCore.QRect(365, 331, 171, 161))
        self.pumpsOffPlot.setObjectName("pumpsOffPlot")
        self.pumpOnLabel = QtWidgets.QLabel(self.centralwidget)
        self.pumpOnLabel.setGeometry(QtCore.QRect(190, 310, 151, 20))
        self.pumpOnLabel.setObjectName("pumpOnLabel")
        self.pumpOffLabel = QtWidgets.QLabel(self.centralwidget)
        self.pumpOffLabel.setGeometry(QtCore.QRect(370, 310, 161, 20))
        self.pumpOffLabel.setObjectName("pumpOffLabel")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.initializeButton.setText(_translate("MainWindow", "Click to Initialize"))
        self.label.setText(_translate("MainWindow", "History:"))
        self.linesPerFrameLabel.setText(_translate("MainWindow", "Lines per frame:"))
        self.pumpOnLabel.setText(_translate("MainWindow", "Avg Pumps On"))
        self.pumpOffLabel.setText(_translate("MainWindow", "Avg Pumps Off"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
