# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'small_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(180, 141, 371, 281))
        self.graphicsView.setObjectName("graphicsView")
        self.linePeriod = QtWidgets.QLineEdit(self.centralwidget)
        self.linePeriod.setGeometry(QtCore.QRect(200, 200, 113, 21))
        self.linePeriod.setText("")
        self.linePeriod.setObjectName("linePeriod")
        self.History = QtWidgets.QTextBrowser(self.centralwidget)
        self.History.setGeometry(QtCore.QRect(335, 170, 211, 241))
        self.History.setObjectName("History")
        self.initializeButton = QtWidgets.QPushButton(self.centralwidget)
        self.initializeButton.setGeometry(QtCore.QRect(180, 240, 151, 32))
        self.initializeButton.setObjectName("initializeButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(410, 150, 60, 16))
        self.label.setObjectName("label")
        self.linePeriodLabel = QtWidgets.QLabel(self.centralwidget)
        self.linePeriodLabel.setGeometry(QtCore.QRect(200, 180, 71, 16))
        self.linePeriodLabel.setObjectName("linePeriodLabel")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.initializeButton.setText(_translate("MainWindow", "Click to Initialize"))
        self.label.setText(_translate("MainWindow", "History:"))
        self.linePeriodLabel.setText(_translate("MainWindow", "Line period:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
